apiVersion: apps/v1
kind: Deployment
metadata:
  name: colegio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colegio-api
  template:
    metadata:
      labels:
        app: colegio-api
    spec:
      containers:
      - name: colegio-api
        image: vcepeda596/colegio-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: colegio
