replicaCount: 1

image:
  repository: tu-usuario-dockerhub/colegio-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080  # puedes cambiarlo si lo necesitas

env:
  MYSQL_HOST: mysql
  MYSQL_PORT: 3306
  MYSQL_USER: root
  MYSQL_PASSWORD: rootpassword
  MYSQL_DATABASE: colegio


